Repository Arquisoft/wiq_es6c, pull requests merged in 2024-04, with the labels that each got.

#90 Bug fixes marco
  .github/workflows/release.yml
  gatewayservice/gateway-service.js
  questionsservice/questiongeneratorservice/questiongenerator-service.js
  storeQuestionService/store-q-service.js
  webapp/public/index.html
  webapp/src/components/Button.jsx
  webapp/src/components/FirstGame.css
  webapp/src/index.css
  webapp/src/userStats/css/Game.css
Labels: bug

#96 Webapp tests marco
  webapp/src/storeQuestion/App.jsx
  webapp/src/storeQuestion/test/App.test.jsx
  webapp/src/userStats/App.jsx
  webapp/src/userStats/test/App.test.jsx
Labels: testing

#100 Finalizadas correcciones de la documentación
  docs/src/05_building_block_view.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation

#101 Questions Services major upgrade
  questionsservice/questiongeneratorservice/questiongenerator-service.js
  questionsservice/questiongeneratorservice/questiongenerator.js
  questionsservice/wikidataExtractor/wikidataextractor-service.js
Labels: development

#115 Añadida nueva plantilla de pregunta:
  questionsservice/questiongeneratorservice/questiongenerator.js
Labels: development
